# ===== SERVIDOR =====
server.port=8082

# ===== SQLITE =====
spring.datasource.url=jdbc:sqlite:src/main/resources/database/centroplus.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# ===== HIBERNATE =====
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ===== JWT =====
jwt.secret=centroplusSuperSecretKeyParaJWT2024!
jwt.expiration=86400000

# ===== SWAGGER =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ===== JPA =====
spring.jpa.open-in-view=false