-- ─── LIMPIEZA ────────────────────────────────────────────────────────────────
DROP TABLE IF EXISTS incidencias_deleted;
DROP TABLE IF EXISTS reservas_deleted;
DROP TABLE IF EXISTS actividades_deleted;
DROP TABLE IF EXISTS usuarios_deleted;
DROP TABLE IF EXISTS remember_tokens;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS incidencias;
DROP TABLE IF EXISTS reservas;
DROP TABLE IF EXISTS actividades;
DROP TABLE IF EXISTS usuarios;

-- ─── USUARIOS ────────────────────────────────────────────────────────────────
CREATE TABLE usuarios (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(255) NOT NULL,
    dni        VARCHAR(20)  NOT NULL UNIQUE,
    email      VARCHAR(255) NOT NULL,
    telefono   VARCHAR(20),
    tipo_usuario VARCHAR(10) NOT NULL CHECK(tipo_usuario IN ('ALUMNO','SOCIO','AMBOS','ADMIN')),
    password   VARCHAR(255) NOT NULL,
    activo     INTEGER      NOT NULL DEFAULT 1,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE usuarios_deleted (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_id BIGINT       NOT NULL,
    nombre      VARCHAR(255),
    dni         VARCHAR(20),
    email       VARCHAR(255),
    telefono    VARCHAR(20),
    tipo_usuario VARCHAR(10),
    password    VARCHAR(255),
    deleted_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ─── ACTIVIDADES ─────────────────────────────────────────────────────────────
CREATE TABLE actividades (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(255) NOT NULL,
    tipo_actividad   VARCHAR(10)  NOT NULL CHECK(tipo_actividad IN ('DEPORTIVA','ACADEMICA')),
    duracion         INTEGER      NOT NULL,
    precio           DOUBLE       NOT NULL CHECK(precio >= 0),
    plazas_maximas   INTEGER      NOT NULL,
    plazas_ocupadas  INTEGER      NOT NULL DEFAULT 0,
    activo           INTEGER      NOT NULL DEFAULT 1,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP
);

CREATE TABLE actividades_deleted (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_id     BIGINT NOT NULL,
    nombre          VARCHAR(255),
    tipo_actividad  VARCHAR(10),
    duracion        INTEGER,
    precio          DOUBLE,
    plazas_maximas  INTEGER,
    plazas_ocupadas INTEGER,
    deleted_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ─── RESERVAS ────────────────────────────────────────────────────────────────
CREATE TABLE reservas (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario   BIGINT       NOT NULL,
    id_actividad BIGINT       NOT NULL,
    fecha        VARCHAR(20)  NOT NULL,
    estado       VARCHAR(15)  NOT NULL CHECK(estado IN ('ACTIVA','CANCELADA','COMPLETADA')),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    FOREIGN KEY (id_usuario)   REFERENCES usuarios(id),
    FOREIGN KEY (id_actividad) REFERENCES actividades(id)
);

CREATE TABLE reservas_deleted (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_id  BIGINT NOT NULL,
    id_usuario   BIGINT,
    id_actividad BIGINT,
    fecha        VARCHAR(20),
    estado       VARCHAR(15),
    deleted_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ─── INCIDENCIAS ─────────────────────────────────────────────────────────────
CREATE TABLE incidencias (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario  BIGINT       NOT NULL,
    asunto      VARCHAR(255) NOT NULL,
    descripcion TEXT         NOT NULL,
    fecha       VARCHAR(20)  NOT NULL,
    estado      VARCHAR(15)  NOT NULL CHECK(estado IN ('ABIERTA','EN_PROCESO','CERRADA')),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id)
);

CREATE TABLE incidencias_deleted (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_id BIGINT NOT NULL,
    id_usuario  BIGINT,
    asunto      VARCHAR(255),
    descripcion TEXT,
    fecha       VARCHAR(20),
    estado      VARCHAR(15),
    deleted_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ─── REMEMBER TOKENS ─────────────────────────────────────────────────────────
CREATE TABLE remember_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES usuarios(id)
);

-- ─── AUDIT LOG ───────────────────────────────────────────────────────────────
CREATE TABLE audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(100) NOT NULL,
    record_id  BIGINT       NOT NULL,
    action     VARCHAR(10)  NOT NULL CHECK(action IN ('INSERT','UPDATE','DELETE')),
    old_data   TEXT,
    new_data   TEXT,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);